### PR TITLE
imp: Reimplementation of field generation to avoid game over on first clik after game beginning

### PR DESCRIPTION
**Pull request by xilec**

### CODE REVIEW

**Comment by Vinatorul** [comment]
Nice idea! 
I saw same behavior in windows minesweeper.
Great :+1:, you can merge if it's done. 

Btw, can you, please, format future commites as in [Contribuion guideline](https://github.com/Vinatorul/minesweeper-rs/blob/master/CONTRIBUTING.md), because I am using `clog` to create changelogs.

**Comment by xilec** [comment]
I try to change name of comment, but, accidentally, I push this  commit (0723d12c42c78c169723414ad72b5dd3575a0163) directly in original repo.

**Comment by Vinatorul** [comment]
Strange, master is protected branch. Looks like an error in github.

**Comment by xilec** [comment]
Protected branch don't prevent branch from new direct commits. It just prevents repo from unrecoverable changes.

**Comment by Vinatorul** [comment]
May be, I have tried to commit directly only via github interface, when I have not got PC near, and it was not allowed. At home I am always working in branches.

**Pull request closed without merging**
