### PR TITLE
fix: true number of mines on board, not the case before

### PR DESCRIPTION
**Pull request by waynenilsen**
If there was a high mine density before, there would not be that many mines on the board. This addresses this issue. I don't know how "fix" suits this commit but that is what I labeled it.

### CODE REVIEW

**Comment by Vinatorul** [comment]
Looks great! Thank you! I will merge a little later.

**Comment by dylanhart** [comment]
This could better be implemented by the following:
1. make a list of numbers from 0 to (grid_w \* grid_h)
2. shuffle the list
3. starting from the beginning of the list, put a mine on each index until the number of mines is reached

This would stop the program from checking if a cell is a mine on every mine creation.

**Comment by waynenilsen** [comment]
I think that is exactly what the [`improvement`](https://github.com/waynenilsen/minesweeper-rs/commit/8c7ff7f38ad00763a4b0725d0ca0aa6225337f11) commit does. Funny how you described the exact algorithm that I ended up using.

**Comment by dylanhart** [comment]
Oops didn't see that second commit.

**Comment by Vinatorul** [comment]
:+1: Merged!

**Pull request merged**
