### PR TITLE
feat: added the timer

### LINKED ISSUE #9: Timer
Add timer. Timer must start when first cell opens and stop after winning or loosing game

### PR DESCRIPTION
**Pull request by waynenilsen**
closes #9 

I believe this works as intended. I couldn't figure out how to get the integers to format as two digits with a leading zero if someone could help me that would be great. 

Displays minutes and seconds since first click until game over.

### CODE REVIEW

**Comment by Vinatorul** [comment]
Thank you for implementation idea - I will add some changes, and do PR to your branch.
Don't worry about check fail - there is some problem in nightly with `gfx` again - I will return `nightly` to `allowed failures` before PR to your fork.

**Comment by waynenilsen** [comment]
it looks like i missed some changes, I did these before and i thought they were in the initial commit

**Comment by Vinatorul** [comment]
@waynenilsen fell free to push here, just do not rebase, please

**Comment by Vinatorul** [comment]
Yeh! Now it works as supposed, I will add some style changes than and merge to `master`

**Comment by Vinatorul** [comment]
When #37 will be merged - you can update and rebase this, so I will merge after checks will pass.

**Comment by Vinatorul** [comment]
:+1: merged

**Pull request merged**
